# Part of Odoo. See LICENSE file for full copyright and licensing details.

import logging

from odoo import models, fields
from odoo.tools import html2plaintext, plaintext2html

_logger = logging.getLogger(__name__)

ESCALATION_KEYWORDS = [
    '人工', '客服', '转人工', '真人', '投诉', '退款', '举报',
    'human', 'agent', 'refund', 'complaint',
    'Human', 'Customer Service', 'Transfer to Human', 'Live', 'Complaint', 'Refund', 'Report',
    '人工', '客服', '轉人工', '真人', '投訴', '退款', '舉報',
]

# Message types generated by the system — not considered human replies
_SYSTEM_MESSAGE_TYPES = ('notification', 'email', 'auto_comment', 'user_notification')


class DiscussChannel(models.Model):
    _inherit = 'discuss.channel'

    ai_mode = fields.Selection(
        selection=[('ai', 'AI Auto Reply'), ('human', 'Human')],
        string='Handling Mode',
        default='ai',
    )

    def message_post(self, **kwargs):
        msg = super().message_post(**kwargs)

        if self.channel_type != 'whatsapp':
            return msg

        has_inbound_uid = bool(kwargs.get('whatsapp_inbound_msg_uid'))
        message_type = kwargs.get('message_type', '')

        # ── Case A: Inbound customer message → trigger AI ─────────────────────
        if has_inbound_uid and message_type == 'whatsapp_message' and self.ai_mode == 'ai':
            account = getattr(self, 'wa_account_id', False)

            if not (account and account.enable_ai and account.ai_agent_id):
                _logger.warning('[AI] Not enabled or agent not configured | channel=%s', self.id)
                return msg

            customer_text = html2plaintext(kwargs.get('body', '')).strip()
            if not customer_text:
                return msg

            _logger.info('[AI] Inbound text="%s" | channel=%s', customer_text[:80], self.id)

            self.env.cr.postcommit.add(
                lambda ch=self, txt=customer_text,
                       ag=account.ai_agent_id,
                       uid=kwargs['whatsapp_inbound_msg_uid'],
                       mid=msg.id:
                ch._do_ai_reply(txt, ag, uid, mid)
            )

        # ── Case B: Outbound non-system message → detect human takeover ────────
        elif (
                not has_inbound_uid
                and self.ai_mode == 'ai'
                and message_type not in _SYSTEM_MESSAGE_TYPES
        ):
            odoobot_id = self.env.ref('base.partner_root').id
            customer_id = self.whatsapp_partner_id.id if self.whatsapp_partner_id else None
            author_id = kwargs.get('author_id')

            if author_id and author_id not in (odoobot_id, customer_id):
                _logger.info('[AI] Human takeover detected | channel=%s | author=%s',
                             self.id, author_id)
                self.sudo().write({'ai_mode': 'human'})
                self.message_post(
                    body='👤 Human agent has taken over. AI has been paused.',
                    message_type='notification',
                )

        return msg

    # ── Manual buttons ────────────────────────────────────────────────────────

    def action_take_over(self):
        self.sudo().write({'ai_mode': 'human'})
        self.message_post(body='👤 Human agent has taken over. AI has been paused.',
                          message_type='notification')

    def action_return_to_ai(self):
        self.sudo().write({'ai_mode': 'ai'})
        self.message_post(body='🤖 Switched back to AI.',
                          message_type='notification')

    # ── Postcommit entry ──────────────────────────────────────────────────────

    def _do_ai_reply(self, customer_text, agent, inbound_uid, inbound_msg_id):
        try:
            self._ai_auto_reply(customer_text, agent, inbound_uid, inbound_msg_id)
            self.env.cr.commit()
        except Exception:
            _logger.exception('[AI] Unhandled error in _do_ai_reply | channel=%s', self.id)
            self.env.cr.rollback()

    # ── Core AI reply logic ───────────────────────────────────────────────────

    def _ai_auto_reply(self, customer_text, agent, inbound_uid=None, inbound_msg_id=None):
        self.ensure_one()

        # Deduplication: skip if AI already replied after this inbound message
        if inbound_msg_id:
            odoobot_id = self.env.ref('base.partner_root').id
            already_replied = self.env['mail.message'].sudo().search_count([
                ('res_id', '=', self.id),
                ('model', '=', 'discuss.channel'),
                ('author_id', '=', odoobot_id),
                ('id', '>', inbound_msg_id),
            ], limit=1)
            if already_replied:
                _logger.info('[AI] Duplicate detected, skipping | channel=%s', self.id)
                return

        # Mode check before calling LLM
        self.invalidate_recordset(['ai_mode'])
        if self.ai_mode != 'ai':
            _logger.info('[AI] Mode is "%s", aborting | channel=%s', self.ai_mode, self.id)
            return

        # 24-hour window check
        valid_until = self.whatsapp_channel_valid_until
        if valid_until and valid_until < fields.Datetime.now():
            _logger.warning('[AI] 24h window expired | channel=%s', self.id)
            return

        # Escalation keyword check
        if self._ai_should_escalate(customer_text):
            self._ai_escalate(reason='Customer requested human')
            return

        # Call AI Agent
        _logger.info('[AI] Calling agent=%s | channel=%s', agent.id, self.id)
        try:
            message_body = agent._generate_response_for_whatsapp(customer_text, self)
        except Exception:
            _logger.exception('[AI] Agent call failed | channel=%s', self.id)
            self._ai_escalate(reason='AI service error')
            return

        if not message_body:
            _logger.warning('[AI] Agent returned empty response | channel=%s', self.id)
            return

        # Mode check after LLM call — human may have intervened during processing
        self.invalidate_recordset(['ai_mode'])
        if self.ai_mode != 'ai':
            _logger.info('[AI] Human intervened during LLM call, discarding response | channel=%s',
                         self.id)
            return

        self.message_post(
            body=plaintext2html(message_body),
            message_type='whatsapp_message',
            subtype_xmlid='mail.mt_comment',
            author_id=self.env.ref('base.partner_root').id,
        )
        _logger.info('[AI] Reply sent | channel=%s | length=%d', self.id, len(message_body))

    def _ai_should_escalate(self, text):
        text_lower = (text or '').lower()
        matched = [kw for kw in ESCALATION_KEYWORDS if kw in text_lower]
        if matched:
            _logger.info('[AI] Escalation keywords matched: %s | channel=%s', matched, self.id)
        return bool(matched)

    def _ai_escalate(self, reason='Customer request'):
        _logger.info('[AI] Escalating to human | reason=%s | channel=%s', reason, self.id)
        self.sudo().write({'ai_mode': 'human'})
        self.message_post(
            body='Sorry, transferring you to a human agent. Please wait...',
            message_type='whatsapp_message',
            subtype_xmlid='mail.mt_comment',
            author_id=self.env.ref('base.partner_root').id,
        )
        self.message_post(
            body=f'⚠️ Escalation reason: {reason}. Please take over.',
            message_type='notification',
        )
